// packages/playground-vue/src/components/combobox/combobox-virtualized.vue
<template>
  <div class="flex">
    <Example :virtual="true" />
    <Example :virtual="false" />
  </div>
</template>

<script setup>
import { timezones as allTimezones } from '../../data'
import { ref, defineComponent, computed } from 'vue'
import {
  Combobox,
  ComboboxButton,
  ComboboxInput,
  ComboboxLabel,
  ComboboxOption,
  ComboboxOptions,
} from '@headlessui/vue'

let html = String.raw
let Example = defineComponent({
  name: 'Example',
  components: {
    Combobox,
    ComboboxButton,
    ComboboxInput,
    ComboboxLabel,
    ComboboxOption,
    ComboboxOptions,
  },
  props: {
    virtual: {
      type: Boolean,
      default: false,
    },
  },
  setup() {
    let query = ref('')
    let activeTimezone = ref(allTimezones[2])
    let timezones = computed(() => {
      return query.value === ''
        ? allTimezones
        : allTimezones.filter((timezone) =>
            timezone.toLowerCase().includes(query.value.toLowerCase())
          )
    })

    return { query, activeTimezone, timezones }
  },
  template: html`
    <div class="flex h-full w-screen justify-center bg-gray-50 p-12">
      <div class="mx-auto w-full max-w-xs">
        <div class="py-8 font-mono text-xs">Selected timezone: {{ activeTimezone }}</div>
        <div class="space-y-1">
          <Combobox v-model="activeTimezone" as="div">
            <ComboboxLabel class="block text-sm font-medium leading-5 text-gray-700">
              Timezone {{ virtual ? '(virtual)' : ''}}
            </ComboboxLabel>

            <div class="relative">
              <span
                class="relative inline-flex flex-row overflow-hidden rounded-md border shadow-sm"
              >
                <ComboboxInput
                  @change="query = $event.target.value"
                  class="border-none px-3 py-1 outline-none"
                />
                <ComboboxButton
                  class="cursor-default border-l bg-gray-100 px-1 text-indigo-600 focus:outline-none"
                >
                  <span class="pointer-events-none flex items-center px-2">
                    <svg
                      class="h-5 w-5 text-gray-400"
                      viewBox="0 0 20 20"
                      fill="none"
                      stroke="currentColor"
                    >
                      <path
                        d="M7 7l3-3 3 3m0 6l-3 3-3-3"
                        strokeWidth="1.5"
                        strokeLinecap="round"
                        strokeLinejoin="round"
                      />
                    </svg>
                  </span>
                </ComboboxButton>
              </span>

              <div class="absolute mt-1 w-full rounded-md bg-white shadow-lg">
                <ComboboxOptions
                  class="shadow-xs max-h-60 overflow-auto rounded-md py-1 text-base leading-6 focus:outline-none sm:text-sm sm:leading-5"
                >
                  <ComboboxOption
                    v-for="(timezone, idx) in timezones"
                    :key="timezone"
                    :value="timezone"
                    :order="virtual ? idx : undefined"
                    v-slot="{ active, selected }"
                  >
                    <div
                      :class="[
                        'relative cursor-default select-none py-2 pl-3 pr-9 focus:outline-none',
                        active ? 'bg-indigo-600 text-white' : 'text-gray-900',
                      ]"
                    >
                      <span :class="['block truncate', selected ? 'font-semibold' : 'font-normal']">
                        {{ timezone }}
                      </span>
                      <span
                        v-if="selected"
                        :class="[
                          'absolute inset-y-0 right-0 flex items-center pr-4',
                          active ? 'text-white' : 'text-indigo-600',
                        ]"
                      >
                        <svg class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
                          <path
                            fillRule="evenodd"
                            d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z"
                            clipRule="evenodd"
                          />
                        </svg>
                      </span>
                    </div>
                  </ComboboxOption>
                </ComboboxOptions>
              </div>
            </div>
          </Combobox>
        </div>
      </div>
    </div>
  `,
})
</script>

// packages/playground-react/pages/combobox/combobox-virtualized.tsx
import React, { useState } from 'react'
import { Combobox } from '@headlessui/react'

import { classNames } from '../../utils/class-names'
import { Button } from '../../components/button'
import { timezones as allTimezones } from '../../data'

export default function Home() {
  return (
    <div className="flex">
      <Example virtual={true} />
      <Example virtual={false} />
    </div>
  )
}

function Example({ virtual = true }: { virtual?: boolean }) {
  let [query, setQuery] = useState('')
  let [activeTimezone, setActiveTimezone] = useState(allTimezones[0])

  let timezones =
    query === ''
      ? allTimezones
      : allTimezones.filter((timezone) => timezone.toLowerCase().includes(query.toLowerCase()))

  return (
    <div className="flex h-full w-screen justify-center bg-gray-50 p-12">
      <div className="mx-auto w-full max-w-xs">
        <div className="py-8 font-mono text-xs">Selected timezone: {activeTimezone}</div>
        <div className="space-y-1">
          <Combobox
            virtual={virtual}
            value={activeTimezone}
            onChange={(value) => {
              setActiveTimezone(value)
              setQuery('')
            }}
            as="div"
          >
            <Combobox.Label className="block text-sm font-medium leading-5 text-gray-700">
              Timezone {virtual ? `(virtual)` : ''}
            </Combobox.Label>

            <div className="relative">
              <span className="relative inline-flex flex-row overflow-hidden rounded-md border shadow-sm">
                <Combobox.Input
                  onChange={(e) => setQuery(e.target.value)}
                  className="border-none px-3 py-1 outline-none"
                />
                <Combobox.Button as={Button}>
                  <span className="pointer-events-none flex items-center px-2">
                    <svg
                      className="h-5 w-5 text-gray-400"
                      viewBox="0 0 20 20"
                      fill="none"
                      stroke="currentColor"
                    >
                      <path
                        d="M7 7l3-3 3 3m0 6l-3 3-3-3"
                        strokeWidth="1.5"
                        strokeLinecap="round"
                        strokeLinejoin="round"
                      />
                    </svg>
                  </span>
                </Combobox.Button>
              </span>

              <div className="absolute mt-1 w-full rounded-md bg-white shadow-lg">
                <Combobox.Options className="shadow-xs max-h-60 overflow-auto rounded-md py-1 text-base leading-6 focus:outline-none sm:text-sm sm:leading-5">
                  {timezones.map((timezone, idx) => {
                    return (
                      <Combobox.Option
                        key={timezone}
                        order={virtual ? idx : undefined}
                        value={timezone}
                        className={({ active }) => {
                          return classNames(
                            'relative w-full cursor-default select-none py-2 pl-3 pr-9 focus:outline-none',
                            active ? 'bg-indigo-600 text-white' : 'text-gray-900'
                          )
                        }}
                      >
                        {({ active, selected }) => (
                          <>
                            <span
                              className={classNames(
                                'block truncate',
                                selected ? 'font-semibold' : 'font-normal'
                              )}
                            >
                              {timezone}
                            </span>
                            {selected && (
                              <span
                                className={classNames(
                                  'absolute inset-y-0 right-0 flex items-center pr-4',
                                  active ? 'text-white' : 'text-indigo-600'
                                )}
                              >
                                <svg className="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
                                  <path
                                    fillRule="evenodd"
                                    d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z"
                                    clipRule="evenodd"
                                  />
                                </svg>
                              </span>
                            )}
                          </>
                        )}
                      </Combobox.Option>
                    )
                  })}
                </Combobox.Options>
              </div>
            </div>
          </Combobox>
        </div>
      </div>
    </div>
  )
}
